src/features/ConfigDataPreview/ConfigDataPreview.tsx
src/features/ConfigDataPreview/configdatapreview.scss
src/features/Configuration/boardControllerConfigSlice.ts

Fixed some tings in the side panel:
* View config pins/toggles as a list
* View PMIC values as a list
* Better formatting of versions
* Remove JSON strings

NCD-584: Add a better view of the toggle and pmic config

---

Changelog.md
package.json

Changes in this release:
* Added a feedback form
* Added list of supported Development Kits
* Updated dependencies to avoid starting and crashing on old nRF Connect Launcher

Version bump to release v0.1.1

---

src/SidePanel.tsx

This feature will tell users that we are writing the configuration to the DK, by greying the "Write config"-button on click. After the write is finished, we "re-enable" the button, indicating that the write is finished. (In addition to logging "Configuration written")

NCD-660: Disable write button on click, enable on write finished

---

Changelog.md
package.json

Changelog:
-   Preliminary support for nRF54L15-DK (rev. 0.2.x and 0.3.0)

Bump version to release v0.1.3. Updated Changelog

---

Changelog.md
package-lock.json
package.json
src/SidePanel.tsx
src/app/DeviceSelector.tsx
src/features/ConfigDataPreview/ConfigDataPreview.tsx
src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
src/features/ConfigSwitch/ConfigSwitch.tsx
src/features/Configuration/Configuration.tsx
src/features/Configuration/boardControllerConfigSlice.ts
src/features/Configuration/hardwareConfiguration.ts

* Read configuration from firmware, using nrfutil-device commands in shared.
* Wrap configuration and merge with boards defaults from the board definition file
* Set current hardware configuration in state to update GUI

NCD-343: Read configuration, merge with defaults, show in GUI

---

Changelog.md
src/common/boards/nrf_PCA10153_0.9.1_9161.json

* Reword IO expander card to make the feature more understandable
* Change to slide switch

NCD-709: Reword IO expander card, change to slide switch

---

src/common/boards/BoardControllerConfigDefinition.ts
src/common/boards/nrf_PCA10153_0.10.0_9161.json
src/common/boards/nrf_PCA10153_0.9.1_9161.json
src/common/boards/nrf_PCA10156_0.2.0.json
src/common/boards/nrf_PCA10156_0.3.0.json
src/features/Configuration/Configuration.tsx

* Use objects instead of tuples for default pins and ports to avoid typing issues

Update types on default pins in board definition files

---

src/SidePanel.tsx
src/app/DeviceSelector.tsx
src/features/Configuration/Configuration.tsx
src/features/Configuration/boardControllerConfigSlice.ts
src/features/Configuration/boardDefinitions.ts

* Refactor arbritation/selection of board configuration definitions. Prepare for dynamic loading of json-files.
* Make default configuration part of config slice
* Add a "Reset to board default"-button to the sidebar.
Doc notes: This PR adds a button to sidebar

NCD-747: Refactor definition loading, add "Reset to default" button

---

Changelog.md
src/common/boards/nrf_PCA10153_0.10.0_9161.json
src/common/boards/nrf_PCA10156_0.2.0.json
src/common/boards/nrf_PCA10156_0.3.0.json
src/common/boards/nrf_PCA10171_0.2.0_9151.json

Add name and description to PMIC ports

NCD-748: Name PMIC ports

---

Changelog.md
src/common/boards/nrf_PCA10156_0.2.0.json
src/common/boards/nrf_PCA10156_0.3.0.json

- Changed maximum voltage to 3.3V

NCD-764: Fix maximum voltage for nRF54L15-DKs

---

Changelog.md
package.json

* Bumped version
* Updated Changelog
-   Names and descriptions to the PMIC ports
-   Support for nRF54H20-DK r0.7.0
-   Fix maximum voltage for nRF54L15-DKs
-   Fix voltage selections on nRF54H20-PDK

Prepare for release of v0.1.9

---

Changelog.md
package.json

-   Update dependency of pc-nrfconnect-shared to v166
-   Lowered required nRF Connect for Desktop version to 4.4.0.

Prepare for release of v0.1.10

---

Changelog.md
src/features/VoltageConfiguration/VoltageConfiguration.tsx

* Filtering out inapplicable voltage presets
* Refactor voltage preset buttons to functional components
* Make ready for preset values from board definition file

NCD-776: Limit voltage presets to fit the boards range

---

src/features/VCOMConfiguration/VCOMConfiguration.tsx

* Disable and disconnect HWFC when VCOM is disconnected
* Remove enable-label
* Use Material icon to indicate tooltip
UI Changes:
Here the UI is shown with one disconnected and one connected VCOM. The HWFC toggle of the disconnected VCOM is also disconnected in addition to the toggle being disabled.

NCD-768: Fix VCOM component UX

---

Changelog.md
package.json

-   Support for nRF9161-DK r1.0.0, including PMIC configuration.

Prepare for release of v0.2.0

---

src/features/ConfigDataPreview/ConfigDataPreview.tsx

Some CSS classes was changed for clarity, and the PMIC config table was forgotten. This patch fixes it, while also removing some unused class assignments.

NCD-770: Fix some missing classes

---

doc/docs/index.md

Fixed incorrect link.
Reported on Teams.

doc: fix link to nRF Connect for Desktop docs

---

Changelog.md
package.json
src/features/Configuration/boardDefinitions.ts

* Make the board definition with SWD-toggle default for nRF54L15.
* Use old definition on revisions prior to r0.3.0.

NCD-927: Add support for nRF54L15-PDF r0.7.0

---

Changelog.md
package-lock.json
package.json
src/SidePanel.tsx
src/app/DirtyDot.tsx
src/app/dirtydot.scss
src/common/boards/BoardControllerConfigDefinition.ts
src/features/ConfigDataPreview/ConfigDataPreview.tsx
src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
src/features/ConfigSwitch/ConfigSwitch.tsx
src/features/Configuration/boardControllerConfigSlice.ts
src/features/Configuration/boardDefinitions.ts
src/features/VCOMConfiguration/VCOMConfiguration.tsx
src/features/VoltageConfiguration/VoltageConfiguration.tsx

This feature is keeping track of which config is read from the board on connection, and will indicate any deviation from that baseline. If no config is read (ie. the board is not configured) for a pin, the baseline will be the default for the pin.
Dependencies to shared and nrfutil are also updated.

NCD-962: Indicate unwritten changes

---

src/features/VoltageConfiguration/VoltageConfiguration.tsx

Only a single change from this UX review:
* Make the VoltageConfiguration preset buttons active white and inactive grey. (Instead of the opposite.)

NCD-771: UX review of first version

---

Changelog.md

-   Blue dot indicators for configuration options with unwritten changes.
-   Icon and metadata for the nRF54L and nRF54H Series devices.
-   Updated shared components

Prepare for release v0.3.4

---

Changelog.md
package-lock.json
package.json
src/features/Configuration/Configuration.tsx

Added notes for both nRF54L15 and nRF54H20.

NCD-1044: Added nRF54 notes to main screen

---

Changelog.md
package-lock.json
package.json

* Updating to the latest version of nrfutil-device fixes the problem with connection failure when SWDCONTROL is set true in the configuration.

NCD-1101: Update nrfutil-device dependency to v2.7.6
