package.json

Rename application and edit description

Ncd 647 rename app

---

src/common/boards/nrf_PCA10153_0.9.1_9161.json
src/features/VCOMConfiguration/VCOMConfiguration.tsx
src/features/VCOMConfiguration/vcomconfig.scss

Fix descriptive texts about the nRF9161-DK.
* Update board definition file, aligning it with the nRF9161-DK documentation
* Update texts in VCOMConfiguration component to clarify
* Add a tooltip to the VCOM HWFC to clarify and align with the nRF9161-DK

NCD-628-2: Fix texts

---

Changelog.md
package.json

Bump version, add changelog for v0.1.0

---

package.json

Added
* Support reading configuration from board controller

Bump version to release v0.1.4

---

src/features/ConfigDataPreview/ConfigDataPreview.tsx
src/features/Configuration/Configuration.tsx
src/features/VCOMConfiguration/VCOMConfiguration.tsx

features: update tooltips

---

Changelog.md

* Remove the title "Changelog" from Changelog.md

NCD-713: Changelog should not have a title

---

Changelog.md
package.json

Bump version to release v0.1.5. Add changelog entry.

---

src/common/boards/nrf_PCA10153_0.10.0_9161.json

* Update definition for nRF9161 v0.10.0 to be aligned with new tooltips

NCD-745: Update 9161 definition

---

doc/docs/index.md
doc/docs/revision_history.md

Added nRF9151 DK to the list.
NCD-733.

doc: update supported devices list

---

Changelog.md
package-lock.json
package.json

* Bump version to release v0.1.6.
* Add changelog entry.

Prepare for release of v0.1.6

---

Changelog.md
src/common/boards/nrf_PCA10175_54H20_0.7.0.json
src/features/Configuration/boardDefinitions.ts

* Added support for nRF54H20-DK r0.7.0

NCD-774: Support nRF54H20-DK r0.7.0

---

package.json

* Lowered engine dep to 4.4.0 again

Don't depend on engine 4.4.1

---

Changelog.md
package.json

-   Showing only the voltage presets that are in range

Prepare for release of v0.1.11

---

src/features/VoltageConfiguration/VoltageConfiguration.tsx

* Move preset buttons
* Resize buttons
* Move description
* Add some air
*NEW SCREENSHOT*
*NEW SCREENSHOT*

NCD-769: Update UI on VoltageConfiguration component

---

src/common/boards/BoardControllerConfigDefinition.ts
src/common/boards/nrf_PCA10145_54H20.json
src/common/boards/nrf_PCA10153_0.10.0_9161.json
src/common/boards/nrf_PCA10153_0.9.1_9161.json
src/common/boards/nrf_PCA10156_0.2.0.json
src/common/boards/nrf_PCA10156_0.3.0.json
src/common/boards/nrf_PCA10171_0.2.0_9151.json
src/common/boards/nrf_PCA10175_54H20_0.7.0.json
src/features/ConfigSlideSelector/ConfigSlideSelector.tsx
src/features/ConfigSwitch/ConfigSwitch.tsx
src/features/Configuration/Configuration.tsx
src/features/VCOMConfiguration/VCOMConfiguration.tsx

* Removed "Enable" from config switch component
* Rewrite board def to make it easier to understand the options
* Add tooltip capability to the board definition parser and react components
* Make toggle labels clickable
* Improve style

NCD-773: Update UI, improve UX, rewrite board definition files

---

Changelog.md
package.json
src/common/boards/nrf_PCA10156_0.2.0.json

-   Updated texts explaining the board controller options.
-   Updated UI
-   Updated shared components

Release v0.1.12

---

src/features/VoltageConfiguration/VoltageConfiguration.tsx

Rebuild of tailwind CSS might change order of stanzas, and alter rendered style.

NCD-773: Fix style error from tailwind stanza order

---

src/common/boards/nrf_PCA10153_1.0.0_9161.json

* Add PMIC ports to nRF9161-DK r1.0.0 board definition

NCD-822: Support PMIC on nRF9161-DK r1.0.0

---

.github/workflows/zoomin-publish-dev.yml
.github/workflows/zoomin-publish.yml
doc/docs/revision_history.md

Updated the revision history for doc changes applied earlier.

doc: update for v0.20.0

---

package-lock.json
package.json
src/SidePanel.tsx
src/features/BoardInformation/BoardInformation.tsx
src/features/ConfigDataPreview/ConfigDataPreview.tsx
src/features/ConfigDataPreview/configdatapreview.scss
src/features/ConfigJsonRender/ConfigJsonRender.tsx
src/features/Configuration/Configuration.tsx
src/features/Configuration/boardDefinitions.ts
src/index.tsx

* Bump shared dependency 
* Clean up SidePanel buttons
* Clean up typography on BoardInformation
* Implement DIP-switch view of config data
* Clean up PMIC config view
* Make initial version of ConfigJsonRender dialog
* Remove board name in config pane
Config JSON dialog:

NCD-770: Update UI on sidepanel, add config DIP switch component

---

Changelog.md

Prepare for release v0.3.8

---

Changelog.md
package-lock.json
package.json
src/common/boards/nrf_PCA10156_0.3.0.json

* Fixed wording for ledcontrol

NCD-1094: Fix nRF54 L15 LED control wording

---

Changelog.md
package-lock.json
package.json
src/features/ConfigJsonRender/ConfigJsonRender.tsx

Includes:
- nrfutil update 
- https://nordicsemi.atlassian.net/browse/NCD-1151

Release 0.3.11 prepare
